package qna_infra

import (
	"ioprodz/common/policies"
	qna_models "ioprodz/qna/_models"
)

type QNAMemoryRepository struct {
	list []qna_models.QNA
}

func (repo *QNAMemoryRepository) Create(qna qna_models.QNA) {
	repo.list = append(repo.list, qna)
}

func (repo *QNAMemoryRepository) List() []qna_models.QNA {
	return repo.list
}

func (repo *QNAMemoryRepository) Get(id string) (qna_models.QNA, error) {
	for _, obj := range repo.list {
		if obj.Id == id {
			return obj, nil
		}
	}
	return qna_models.QNA{}, &policies.StorageError{Message: "Element not found by id: " + id}
}

func CreateQNARepo() *QNAMemoryRepository {
	repo := &QNAMemoryRepository{list: make([]qna_models.QNA, 0)}
	repo.seed()
	return repo
}

func (repo *QNAMemoryRepository) seed() {
	repo.list = []qna_models.QNA{qna_models.QNAFromJSON([]byte(`
{
	"id": "e0e15972-4e49-46da-bc48-927a9a11fb8d",
	"name":"agile methodologies",
	"questions":[{"value":"What is the primary goal of Agile methodologies?","choices":[{"value":"To follow a strict project plan with no changes.","isCorrect":false},{"value":"To enable teams to deliver value to their customers faster and with fewer headaches.","isCorrect":true},{"value":"To complete projects with as many features as possible.","isCorrect":false},{"value":"To ensure that documentation is prioritized over working software.","isCorrect":false}]},{"value":"Which of the following is a core principle of the Agile Manifesto?","choices":[{"value":"Processes and tools over individuals and interactions.","isCorrect":false},{"value":"Comprehensive documentation over working software.","isCorrect":false},{"value":"Customer collaboration over contract negotiation.","isCorrect":true},{"value":"Following a plan over responding to change.","isCorrect":false}]},{"value":"What is a Sprint in Agile methodologies?","choices":[{"value":"A long, undefined period where any type of work can be done.","isCorrect":false},{"value":"A fixed-length iteration where a team works to complete a set amount of work.","isCorrect":true},{"value":"A meeting where the team discusses their progress on the project.","isCorrect":false},{"value":"A type of retrospective meeting at the end of a project.","isCorrect":false}]},{"value":"Which of these Agile frameworks emphasizes software development?","choices":[{"value":"Lean","isCorrect":false},{"value":"Scrum","isCorrect":true},{"value":"Kanban","isCorrect":false},{"value":"Six Sigma","isCorrect":false}]},{"value":"What role is responsible for removing impediments and facilitating the team’s progress in Scrum?","choices":[{"value":"Product Owner","isCorrect":false},{"value":"Scrum Master","isCorrect":true},{"value":"Team Lead","isCorrect":false},{"value":"Project Manager","isCorrect":false}]}]
}
`)), qna_models.QNAFromJSON([]byte(`
{
	"id": "ecbc2331-378c-4ba8-9475-a8cd62453bef",
	"name":"DORA Metrics",
	"questions":[{"value":"What does DORA stand for in the context of DevOps?","choices":[{"value":"DevOps Research and Assessment","isCorrect":true},{"value":"Development Operations and Research Analytics","isCorrect":false},{"value":"Digital Operations and Research Association","isCorrect":false},{"value":"DevOps Resource and Analysis","isCorrect":false}]},{"value":"Which of the following is NOT one of the four key DORA metrics?","choices":[{"value":"Lead Time for Changes","isCorrect":false},{"value":"Change Failure Rate","isCorrect":false},{"value":"Mean Time to Restore (MTTR)","isCorrect":true},{"value":"Deployment Frequency","isCorrect":false}]},{"value":"What does the 'Deployment Frequency' DORA metric measure?","choices":[{"value":"The average time it takes to restore a service after a failure","isCorrect":false},{"value":"The percentage of changes to production that fail","isCorrect":false},{"value":"How often an organization successfully releases to production","isCorrect":true},{"value":"The time it takes to go from code committed to code successfully running in production","isCorrect":false}]},{"value":"Why is 'Lead Time for Changes' an important DORA metric?","choices":[{"value":"It indicates the overall satisfaction of the development team","isCorrect":false},{"value":"It measures the security compliance of the deployed changes","isCorrect":false},{"value":"It helps in identifying bottlenecks in the deployment pipeline","isCorrect":true},{"value":"It shows how frequently the team engages with stakeholders","isCorrect":false}]},{"value":"What is the significance of the 'Change Failure Rate' metric?","choices":[{"value":"It measures the team's ability to execute deployments without causing service disruptions","isCorrect":true},{"value":"It calculates the total number of changes made to the codebase in a given period","isCorrect":false},{"value":"It evaluates the effectiveness of the post-deployment testing process","isCorrect":false},{"value":"It indicates the speed at which the team can deliver new features","isCorrect":false}]}]
}
`)), qna_models.QNAFromJSON([]byte(`
{
	"id": "f0fd8c8f-2b72-4026-a9ba-252169da0f90",
	"name":"unit testing",
	"questions":[{"value":"What is the primary purpose of unit testing?","choices":[{"value":"To check the system’s performance under load","isCorrect":false},{"value":"To verify the individual parts of the code work as expected","isCorrect":true},{"value":"To evaluate the user interface design","isCorrect":false},{"value":"To conduct security and vulnerability assessments","isCorrect":false}]},{"value":"Which of the following is NOT a characteristic of a good unit test?","choices":[{"value":"It should run quickly","isCorrect":false},{"value":"It should depend on external data sources","isCorrect":true},{"value":"It should be repeatable in any environment","isCorrect":false},{"value":"It should be isolated from other tests","isCorrect":false}]},{"value":"What is meant by 'test coverage' in the context of unit testing?","choices":[{"value":"The amount of testing time spent by the QA team","isCorrect":false},{"value":"The percentage of code executed by the tests","isCorrect":true},{"value":"The number of bugs found during the testing phase","isCorrect":false},{"value":"The total number of tests written for a module","isCorrect":false}]},{"value":"Which of the following tools is used for unit testing in the JavaScript ecosystem?","choices":[{"value":"Selenium","isCorrect":false},{"value":"Jest","isCorrect":true},{"value":"Postman","isCorrect":false},{"value":"Wireshark","isCorrect":false}]},{"value":"In unit testing, what is a 'mock'?","choices":[{"value":"A part of the code that is ignored during testing","isCorrect":false},{"value":"A bug introduced intentionally for testing the debugging process","isCorrect":false},{"value":"An object that simulates the behavior of real objects in controlled ways","isCorrect":true},{"value":"A copy of the production database used for testing","isCorrect":false}]}]
}
`)), qna_models.QNAFromJSON([]byte(`
{
	"id": "f0fd8c8f-2b72-4026-a9ba-152169da0fdd",
	"name":"software architecture",
	"questions":[{"value":"What is software architecture?","choices":[{"value":"The process of defining a structured solution to meet all the technical and operational requirements.","isCorrect":true},{"value":"The graphical design of a software application's user interface.","isCorrect":false},{"value":"A step-by-step procedure used to solve a problem.","isCorrect":false},{"value":"A programming language used to create software applications.","isCorrect":false}]},{"value":"Which of the following is NOT a common architectural pattern?","choices":[{"value":"Microkernel","isCorrect":false},{"value":"Layered (n-tier) architecture","isCorrect":false},{"value":"Event-driven architecture","isCorrect":false},{"value":"Polymorphic architecture","isCorrect":true}]},{"value":"What is the main goal of the Model-View-Controller (MVC) architecture?","choices":[{"value":"To ensure that an application can run on any operating system.","isCorrect":false},{"value":"To separate an application into three main logical components: the model, the view, and the controller.","isCorrect":true},{"value":"To enhance the security of web applications by strictly separating the database and the user interface.","isCorrect":false},{"value":"To reduce the size of an application to improve load times.","isCorrect":false}]},{"value":"What does the term 'loose coupling' refer to in software architecture?","choices":[{"value":"Components are designed with little or no knowledge of other components.","isCorrect":true},{"value":"The process of removing unnecessary components from an application.","isCorrect":false},{"value":"A style of programming where functions are passed as arguments.","isCorrect":false},{"value":"A temporary fix for a software bug.","isCorrect":false}]},{"value":"Which principle emphasizes that a software component should be extended without modifying it?","choices":[{"value":"KISS (Keep It Simple, Stupid)","isCorrect":false},{"value":"DRY (Don't Repeat Yourself)","isCorrect":false},{"value":"Open/Closed Principle","isCorrect":true},{"value":"Single Responsibility Principle","isCorrect":false}]}]
}
`)), qna_models.QNAFromJSON([]byte(`
{
	"id": "f0fd8c8f-2b72-4026-a9ba-152169da0f3a",
	"name":"cohesion and coupling",
	"questions":[{"value":"What does 'cohesion' refer to in software engineering?","choices":[{"value":"The level of dependency between various modules of a software.","isCorrect":false},{"value":"The measure of how closely related and focused the responsibilities of a single module are.","isCorrect":true},{"value":"The process of breaking a software program into manageable units.","isCorrect":false},{"value":"The practice of optimizing operational efficiency of a software.","isCorrect":false}]},{"value":"Which of the following best describes 'tight coupling'?","choices":[{"value":"Modules are designed with a clear and direct line of communication.","isCorrect":false},{"value":"Modules can function independently without reliance on each other.","isCorrect":false},{"value":"Modules are highly dependent on each other's interfaces.","isCorrect":true},{"value":"Modules share minimal information with each other.","isCorrect":false}]},{"value":"Which level of cohesion is generally considered the most desirable?","choices":[{"value":"Logical cohesion","isCorrect":false},{"value":"Temporal cohesion","isCorrect":false},{"value":"Functional cohesion","isCorrect":true},{"value":"Coincidental cohesion","isCorrect":false}]},{"value":"In terms of software design, what is the primary goal of reducing coupling?","choices":[{"value":"To increase the processing speed of the software.","isCorrect":false},{"value":"To make the software more secure against external threats.","isCorrect":false},{"value":"To enhance the modularity of the software, making it easier to modify and maintain.","isCorrect":true},{"value":"To reduce the overall size of the software.","isCorrect":false}]},{"value":"What is an example of achieving high cohesion within a module?","choices":[{"value":"A module that handles both data storage and user interface rendering.","isCorrect":false},{"value":"A module that is responsible for all operations related to customer information management.","isCorrect":true},{"value":"A module that performs different tasks based on the time of the day it is executed.","isCorrect":false},{"value":"A module that relies on global variables for its operations.","isCorrect":false}]}]
}
`)), qna_models.QNAFromJSON([]byte(`
{
	"id": "ecece544-2a1d-4177-b899-d914fead662f",
	"name":"git commands",
	"questions":[{"value":"What does the 'git clone' command do?","choices":[{"value":"Creates a new branch","isCorrect":false},{"value":"Copies a git repository from a remote source","isCorrect":true},{"value":"Commits staged changes to the repository","isCorrect":false},{"value":"Deletes a repository","isCorrect":false}]},{"value":"Which command shows the commit history for the current repository?","choices":[{"value":"git log","isCorrect":true},{"value":"git commit","isCorrect":false},{"value":"git status","isCorrect":false},{"value":"git show","isCorrect":false}]},{"value":"How do you switch to a different branch?","choices":[{"value":"git switch <branch-name>","isCorrect":true},{"value":"git checkout <branch-name>","isCorrect":true},{"value":"git branch <branch-name>","isCorrect":false},{"value":"git merge <branch-name>","isCorrect":false}]},{"value":"What command do you use to stage changes for a commit?","choices":[{"value":"git add <file>","isCorrect":true},{"value":"git commit <file>","isCorrect":false},{"value":"git push <file>","isCorrect":false},{"value":"git stage <file>","isCorrect":false}]},{"value":"Which command is used to update your local repository to the newest commit?","choices":[{"value":"git commit","isCorrect":false},{"value":"git pull","isCorrect":true},{"value":"git push","isCorrect":false},{"value":"git fetch","isCorrect":false}]}]
}
`)), qna_models.QNAFromJSON([]byte(`
{
	"id": "1d94ed25-22cc-4e7e-a6dc-95ce346e2802",
	"name":"static code analysis",
	"questions":[{"value":"What is the primary purpose of static code analysis?","choices":[{"value":"To compile code into machine language","isCorrect":false},{"value":"To evaluate the code's performance at runtime","isCorrect":false},{"value":"To identify potential errors and vulnerabilities in code without executing it","isCorrect":true},{"value":"To enhance the graphical user interface of applications","isCorrect":false}]},{"value":"Which of the following is a common tool used for static code analysis in Java?","choices":[{"value":"JIRA","isCorrect":false},{"value":"SonarQube","isCorrect":true},{"value":"Docker","isCorrect":false},{"value":"Kubernetes","isCorrect":false}]},{"value":"What does SAST (Static Application Security Testing) focus on?","choices":[{"value":"Testing the application's user interface","isCorrect":false},{"value":"Analyzing the application's source code for security vulnerabilities","isCorrect":true},{"value":"Assessing the application's performance under load","isCorrect":false},{"value":"Monitoring the application in production for security threats","isCorrect":false}]},{"value":"Which of the following can static code analysis NOT directly identify?","choices":[{"value":"Syntax errors","isCorrect":false},{"value":"Memory leaks","isCorrect":false},{"value":"Race conditions","isCorrect":true},{"value":"Security vulnerabilities","isCorrect":false}]},{"value":"True or False: Static code analysis should be used exclusively for ensuring code quality and security.","choices":[{"value":"True","isCorrect":false},{"value":"False","isCorrect":true}]}]
}
`)), qna_models.QNAFromJSON([]byte(`
{
	"id": "f2717b10-e4e2-4db9-bb48-c70ffc9710ff",
	"name":"devOps",
	"questions":[{"value":"What is the primary goal of DevOps?","choices":[{"value":"To improve deployment frequency","isCorrect":false},{"value":"To shorten the system development life cycle while delivering features, fixes, and updates frequently in close alignment with business objectives","isCorrect":true},{"value":"To increase individual productivity","isCorrect":false},{"value":"To solely improve the security of applications","isCorrect":false}]},{"value":"Which of the following is a popular DevOps automation tool?","choices":[{"value":"Microsoft Word","isCorrect":false},{"value":"Jenkins","isCorrect":true},{"value":"Adobe Photoshop","isCorrect":false},{"value":"Notepad++","isCorrect":false}]},{"value":"What is a common practice in DevOps for managing code versions?","choices":[{"value":"Continuous Feedback","isCorrect":false},{"value":"Configuration Management","isCorrect":false},{"value":"Continuous Integration","isCorrect":true},{"value":"Manual Code Review","isCorrect":false}]},{"value":"Which of the following is considered a benefit of implementing DevOps?","choices":[{"value":"Increased Development Cost","isCorrect":false},{"value":"Longer Time to Market","isCorrect":false},{"value":"Higher Software Quality","isCorrect":true},{"value":"Decreased Collaboration between Teams","isCorrect":false}]},{"value":"What does 'Infrastructure as Code' (IaC) mean in DevOps?","choices":[{"value":"Writing documentation for infrastructure manually","isCorrect":false},{"value":"The process of managing and provisioning computer data centers through machine-readable definition files, rather than physical hardware configuration or interactive configuration tools","isCorrect":true},{"value":"The manual setup of servers","isCorrect":false},{"value":"Using code to perform automatic daily backups","isCorrect":false}]}]
}
`)), qna_models.QNAFromJSON([]byte(`
{
	"id": "0e5b89f2-4ad3-4a1a-87c0-6218aa6a3852",
	"name":"l'industrie 4.0",
	"questions":[{"value":"Qu'est-ce que l'industrie 4.0?","choices":[{"value":"La première révolution industrielle basée sur l'utilisation de machines à vapeur.","isCorrect":false},{"value":"L'intégration des technologies numériques et de l'Internet des objets dans le secteur manufacturier.","isCorrect":true},{"value":"Une stratégie de marketing développée dans les années 1990.","isCorrect":false},{"value":"Un concept de gestion de chaîne d'approvisionnement.","isCorrect":false}]},{"value":"Quel est le rôle de l'intelligence artificielle dans l'industrie 4.0?","choices":[{"value":"Remplacer tous les emplois humains par des machines.","isCorrect":false},{"value":"Fournir des analyses prédictives pour la maintenance et l'optimisation des processus de production.","isCorrect":true},{"value":"Développer des jeux vidéo plus sophistiqués.","isCorrect":false},{"value":"Contrôler exclusivement les réseaux sociaux.","isCorrect":false}]},{"value":"Quelle est l'importance de la cybersécurité dans l'industrie 4.0?","choices":[{"value":"Mineure, car les systèmes industriels ne sont pas ciblés par les cyberattaques.","isCorrect":false},{"value":"Cruciale, car la connectivité accrue et l'intégration des systèmes exposent à des risques de sécurité plus élevés.","isCorrect":true},{"value":"Inexistante, car les technologies de l'industrie 4.0 sont infaillibles.","isCorrect":false},{"value":"Limitée aux logiciels, sans impact sur le matériel.","isCorrect":false}]},{"value":"Comment l'Internet des objets (IoT) contribue-t-il à l'industrie 4.0?","choices":[{"value":"En permettant la communication uniquement entre appareils mobiles.","isCorrect":false},{"value":"En connectant machines, systèmes et personnes pour améliorer l'efficacité et la productivité.","isCorrect":true},{"value":"Il n'a pas de contribution significative à l'industrie 4.0.","isCorrect":false},{"value":"En augmentant le coût de la production uniquement.","isCorrect":false}]},{"value":"Quels sont les avantages de la fabrication additive dans l'industrie 4.0?","choices":[{"value":"La réduction des coûts de production et la capacité de produire en masse uniquement.","isCorrect":false},{"value":"L'augmentation du temps de production et la diminution de la qualité des produits.","isCorrect":false},{"value":"La personnalisation des produits, la réduction des délais de production et la diminution du gaspillage de matériel.","isCorrect":true},{"value":"Elle ne présente aucun avantage par rapport aux méthodes de fabrication traditionnelles.","isCorrect":false}]}]
}
`)), qna_models.QNAFromJSON([]byte(`
{
	"id": "51a39ea7-b35c-4314-a7b1-7c84ff4d2e7e",
	"name":"industry 4.0",
	"questions":[{"value":"What does Industry 4.0 primarily focus on?","choices":[{"value":"Manual labor in manufacturing","isCorrect":false},{"value":"Automation and data exchange in manufacturing technologies","isCorrect":true},{"value":"Global outsourcing","isCorrect":false},{"value":"Decreasing technology use in production","isCorrect":false}]},{"value":"Which technology is not considered a key component of Industry 4.0?","choices":[{"value":"Internet of Things (IoT)","isCorrect":false},{"value":"Cyber-physical systems","isCorrect":false},{"value":"Blockchain","isCorrect":false},{"value":"Dial-up internet","isCorrect":true}]},{"value":"What role does Artificial Intelligence (AI) play in Industry 4.0?","choices":[{"value":"Decreasing the speed of data analysis","isCorrect":false},{"value":"Eliminating the need for human workers","isCorrect":false},{"value":"Enabling predictive maintenance","isCorrect":true},{"value":"Reducing the importance of data","isCorrect":false}]},{"value":"How does Industry 4.0 affect the labor market?","choices":[{"value":"It creates a higher demand for low-skilled jobs","isCorrect":false},{"value":"It has no significant impact on the labor market","isCorrect":false},{"value":"It increases the demand for highly skilled workers","isCorrect":true},{"value":"It completely eliminates the need for human workers","isCorrect":false}]},{"value":"Which of the following best describes the concept of a 'smart factory' within the context of Industry 4.0?","choices":[{"value":"A factory that only uses solar power","isCorrect":false},{"value":"A factory where all processes are automated and interconnected","isCorrect":true},{"value":"A factory that does not require any form of electricity","isCorrect":false},{"value":"A factory where only robots are employed","isCorrect":false}]}]
}
`)), qna_models.QNAFromJSON([]byte(`
{
	"id": "edbab37b-7ba2-469c-ae2e-b9fead0e8242",
	"name":"Object Oriented Programming",
	"questions":[{"value":"What is the primary purpose of encapsulation in OOP?","choices":[{"value":"To improve the performance of applications","isCorrect":false},{"value":"To hide the internal state of an object from the outside","isCorrect":true},{"value":"To make code run faster","isCorrect":false},{"value":"To increase the size of the codebase","isCorrect":false}]},{"value":"Which of the following is an example of polymorphism?","choices":[{"value":"A function that adds two numbers","isCorrect":false},{"value":"Using a single function to sort different types of data structures","isCorrect":true},{"value":"Creating multiple instances of a class","isCorrect":false},{"value":"Declaring variables","isCorrect":false}]},{"value":"What does the 'inheritance' concept in OOP allow for?","choices":[{"value":"A class to pass on its properties and methods to another class","isCorrect":true},{"value":"A function to inherit properties from another function","isCorrect":false},{"value":"A method to be executed in parallel","isCorrect":false},{"value":"A class to be duplicated","isCorrect":false}]},{"value":"What does the term 'abstraction' refer to in OOP?","choices":[{"value":"Removing all the functionalities of an object","isCorrect":false},{"value":"Hiding complex implementation details and showing only the necessary features of an object","isCorrect":true},{"value":"The process of creating abstract classes","isCorrect":false},{"value":"The division of a program into smaller programs","isCorrect":false}]},{"value":"Which keyword is used to define an interface in Java?","choices":[{"value":"class","isCorrect":false},{"value":"interface","isCorrect":true},{"value":"implements","isCorrect":false},{"value":"extends","isCorrect":false}]}]
}
`)), qna_models.QNAFromJSON([]byte(`
{
	"id": "9d2fbad6-63a4-40dd-a51a-78e0c5c950e5",
	"name":"Event driven architectures",
	"questions":[{"value":"What is the main characteristic of an event-driven architecture?","choices":[{"value":"Synchronous communication between services","isCorrect":false},{"value":"Use of events to trigger and communicate between decoupled services","isCorrect":true},{"value":"Heavy reliance on point-to-point integration","isCorrect":false},{"value":"Centralized data management","isCorrect":false}]},{"value":"Which of the following best describes an 'event' in an event-driven architecture?","choices":[{"value":"A static piece of data stored in a database","isCorrect":false},{"value":"A significant change in state or an update in the system","isCorrect":true},{"value":"A request for data or a service from another component","isCorrect":false},{"value":"A scheduled task that runs at a specific time","isCorrect":false}]},{"value":"What component in an event-driven architecture is responsible for receiving and processing events?","choices":[{"value":"Event listener","isCorrect":true},{"value":"Event trigger","isCorrect":false},{"value":"Event queue","isCorrect":false},{"value":"Event broker","isCorrect":false}]},{"value":"Which pattern is commonly used in event-driven architectures to ensure data consistency across microservices?","choices":[{"value":"API Gateway pattern","isCorrect":false},{"value":"Event sourcing pattern","isCorrect":true},{"value":"Database per service pattern","isCorrect":false},{"value":"Serverless pattern","isCorrect":false}]},{"value":"How do event-driven architectures typically handle failure modes compared to traditional synchronous systems?","choices":[{"value":"By retrying the failed operation immediately","isCorrect":false},{"value":"By decoupling producers and consumers, allowing for more resilient failure handling","isCorrect":true},{"value":"By stopping all operations until the failure is manually resolved","isCorrect":false},{"value":"By using a central orchestrator to manage retries and error handling","isCorrect":false}]}]
}
`))}
}
