DROP TABLE IF EXISTS answers;
DROP TABLE IF EXISTS qna;
DROP TABLE IF EXISTS user_projects;
DROP TABLE IF EXISTS members;
DROP TABLE IF EXISTS curriculums;
DROP TABLE IF EXISTS blogposts;
DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS user_accounts;
